const FETCH_POSTS = "FETCH_POSTS";
const UPDATE_POST = "UPDATE_POST";
const DELETE_POST = "DELETE_POST";
const CREATE_POST = "CREATE_POST";

export { FETCH_POSTS, UPDATE_POST, DELETE_POST, CREATE_POST };
